### ISSUE TITLE
Figure out why the verse word order is off about half the time

### ISSUE THREAD

**Issue by pdbradley** [pdbradley/guessref#53]
I make two assumptions and one or both could be wrong:

1.  that when the verses are inserted, that the ids assigned to them are sequential
2. that when the verses are given as a query payload, that the default order is by id

one or both of these is wrong.  I would start by #2, putting an explicit order by id into the query for the verse words.

**Comment by JCTalbott** [comment]
`verse_words(order_by: {created_at: asc}) `
was added in attempt to fix this, do you have an example of it not working?

**Comment by JCTalbott** [comment]
`query MyQuery {
  verse_words(where: {verse_id: {_eq: "21"}}, order_by: {id: asc}) {
    id
    word_text
  }
}`
